package views;

import entities.Trabajador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import services.AreaService;
import services.BdTemporal;
import services.TrabajadorService;
import utils.Constantes;
import utils.ListItem;
import utils.ListItem2;
import utils.StringUtils;

/**
 *
 * @author victortinoco
 */
public class RegistroTrabajadorView extends javax.swing.JFrame {

    private String codTrabajador = null;

    /**
     * Creates new form RegistroEmpresaView
     * @param codTrabajador
     */
    public RegistroTrabajadorView(String codTrabajador) {
        initComponents();
        var modelSede = (DefaultComboBoxModel) cbSede.getModel();

        var listaSedes = BdTemporal.getInstance().getListaSedes();
        for (String[] item : listaSedes) {
         modelSede.addElement(new ListItem2(item[0], item[1]));
        }

        if (codTrabajador != null) {
            lblId.setText("ID: " + codTrabajador);
            this.codTrabajador = codTrabajador;

            Trabajador trabajadorExistente = TrabajadorService.getInstance().obtenerPorCodigo(codTrabajador);
            txtApellido.setText(trabajadorExistente.getApellido());
            txtNombre.setText(trabajadorExistente.getNombre());
            txtDNI.setText(trabajadorExistente.getNumeroDocumento());
            txtFechaNacimiento.setLocalDate(trabajadorExistente.getFechaNacimiento());
            
            if (trabajadorExistente.getCodArea()!= null) {
                var area = AreaService.getInstance().obtenerPorCodigo(trabajadorExistente.getCodArea());
                String nombreSede = AreaService.getInstance().obtenerNombreSede(area.getCodSede());
                
                cbSede.setSelectedItem(new ListItem2(area.getCodSede(), nombreSede));
                cbArea.setSelectedItem(new ListItem(area.getCodArea(), area.getNombre()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblErrorEmpresa = new javax.swing.JLabel();
        cbSede = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblErrorArea = new javax.swing.JLabel();
        cbArea = new javax.swing.JComboBox<>();
        lblErrorNombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblErrorApellido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblErrorFechaNacimiento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFechaNacimiento = new utils.SelectorFecha();
        lblErrorDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblId.setText("Nuevo registro");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Sede");

        lblErrorEmpresa.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorEmpresa.setText("Requerido");

        cbSede.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSedeItemStateChanged(evt);
            }
        });

        jLabel4.setText("Área");

        lblErrorArea.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorArea.setText("Requerido");

        cbArea.setEnabled(false);

        lblErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorNombre.setText("Requerido");

        jLabel7.setText("Nombre");

        lblErrorApellido.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorApellido.setText("Requerido");

        jLabel8.setText("Apellido");

        lblErrorFechaNacimiento.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorFechaNacimiento.setText("Requerido");

        jLabel9.setText("Fecha de nacimiento");

        lblErrorDNI.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorDNI.setText("Requerido");

        jLabel10.setText("DNI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblErrorNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblErrorApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorFechaNacimiento)
                                    .addComponent(jLabel9))
                                .addGap(109, 109, 109)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(lblErrorDNI)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(87, 87, 87)
                                .addComponent(btnRegresar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSede, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblErrorEmpresa)
                                .addGap(170, 170, 170)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblErrorArea)
                                .addGap(170, 170, 170))
                            .addComponent(cbArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblId)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorApellido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorDNI))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addComponent(lblErrorFechaNacimiento)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorEmpresa)
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnRegresar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorArea)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        var view = new BandejaTrabajadoresView();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // ocultamos los textos de error
        this.ocultarTextosError();
        
        ListItem2 sedeSeleccionada = (ListItem2) cbSede.getSelectedItem();
        ListItem areaSeleccionada = (ListItem) cbArea.getSelectedItem();

        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String dni = txtDNI.getText().trim();

        if (sedeSeleccionada == null) {
            lblErrorEmpresa.setVisible(true);
            cbSede.setBorder(Constantes.ERROR_BORDER);
            return;
        }
        if (areaSeleccionada == null) {
            lblErrorArea.setVisible(true);
            cbArea.setBorder(Constantes.ERROR_BORDER);
            return;
        }
        
        if (StringUtils.isEmpty(nombre)) {
            lblErrorNombre.setVisible(true);
            txtNombre.setBorder(Constantes.ERROR_BORDER);
            return;
        }
        if (StringUtils.isEmpty(apellido)) {
            lblErrorApellido.setVisible(true);
            txtApellido.setBorder(Constantes.ERROR_BORDER);
            return;
        }
        if (StringUtils.isEmpty(dni)) {
            lblErrorDNI.setVisible(true);
            txtDNI.setBorder(Constantes.ERROR_BORDER);
            return;
        }

        int resp = JOptionPane.showConfirmDialog(rootPane, "¿Desea registrar al trabajador?", "Registrar", JOptionPane.YES_NO_OPTION);

        if (resp != JOptionPane.YES_OPTION) {
            return;
        }

        var trabajador = new Trabajador();
        trabajador.setCodArea(areaSeleccionada.getValor());
        trabajador.setNombre(nombre);
        trabajador.setApellido(apellido);
        trabajador.setNumeroDocumento(dni);
        trabajador.setFechaNacimiento(txtFechaNacimiento.getLocalDate());
        trabajador.setActivo(true);

        if (this.codTrabajador == null) {
            TrabajadorService.getInstance().registrarDatos(trabajador);
        } else {
            trabajador.setCodigoTrabajador(codTrabajador);
            TrabajadorService.getInstance().actualizarDatos(trabajador);
        }

        JOptionPane.showMessageDialog(rootPane, "Registro completado", "Completado", JOptionPane.INFORMATION_MESSAGE);
        this.btnRegresarActionPerformed(null);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbSedeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSedeItemStateChanged
        var modelArea = (DefaultComboBoxModel) cbArea.getModel();
        modelArea.removeAllElements();

        ListItem2 sede = (ListItem2) cbSede.getSelectedItem();

        if (sede == null) {
            return;
        }

        modelArea.addAll(AreaService.getInstance().listarAreasPorSedeCombo(sede.getValor()));

        cbArea.setEnabled(true);
    }//GEN-LAST:event_cbSedeItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<ListItem> cbArea;
    private javax.swing.JComboBox<ListItem2> cbSede;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblErrorApellido;
    private javax.swing.JLabel lblErrorArea;
    private javax.swing.JLabel lblErrorDNI;
    private javax.swing.JLabel lblErrorEmpresa;
    private javax.swing.JLabel lblErrorFechaNacimiento;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private utils.SelectorFecha txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void ocultarTextosError() {
        lblErrorArea.setVisible(false);
        lblErrorEmpresa.setVisible(false);
        lblErrorNombre.setVisible(false);
        lblErrorApellido.setVisible(false);
        lblErrorDNI.setVisible(false);
        lblErrorFechaNacimiento.setVisible(false);
 
        cbArea.setBorder(Constantes.DEFAULT_BORDER);
        cbSede.setBorder(Constantes.DEFAULT_BORDER);
        txtApellido.setBorder(Constantes.DEFAULT_BORDER);
        txtNombre.setBorder(Constantes.DEFAULT_BORDER);
        txtFechaNacimiento.setBorder(Constantes.DEFAULT_BORDER);
        txtDNI.setBorder(Constantes.DEFAULT_BORDER);
    }
    
    protected void limpiar() {
        // ocultamos los textos de error
        this.ocultarTextosError();
        codTrabajador = null;
        lblId.setText("Nuevo registro");
        txtNombre.setText("");
        txtApellido.setText("");
        txtFechaNacimiento.setDate(null);
        txtDNI.setText("");
        cbSede.removeAllItems();
        cbArea.removeAllItems();
        cbArea.setEnabled(false);
    }
}
